# Generated by Django 5.1.2 on 2024-11-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_contador',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
