# Generated by Django 5.1.2 on 2024-11-06 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_factura_numero_contador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='contador_mes_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_contador',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
