# Generated by Django 5.1.2 on 2024-10-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoUsuario', models.CharField(choices=[('Inquilino', 'Inquilino'), ('Dueño', 'Dueño')], max_length=50)),
                ('numeroContador', models.CharField(max_length=50)),
            ],
        ),
    ]
